from random import randint #generates random integers for the function that generates a schedule to manipulate
import pprint #just to make the dictionary more readable
#A function that chooses random attributes for each session from provided lists. 
#Generates a new set up every time, but works for this exercise as the names of people etc don't matter.
def generate(title, speaker, room, topic, time, duration, participants):
    event = []
    for i in range(len(title)):
        random_num = randint(1, len(participants)//2)
        random_set = set()
        for j in range(len(participants)):
            if (j+1)%random_num == 0:
                random_set.add(participants[j])
            
        temp = {
        "title": title[i],
        "speaker": speaker[randint(0, len(speaker) - 1)] ,
        "room": room[i//2],
        "topic": topic[randint(0, len(topic) - 1)],
        "time": time[i//4],
        "duration": duration[randint(0, len(duration) - 1)],
        "max_participants": randint(len(random_set), len(participants)),
        "participants": random_set
        }
        event.append(temp)
    return event
#Names for courses etc generated by AI
sessions = ["Building Game Engines in Python", "Architecting Modular Python Code", "Designing Drag-and-Drop UIs", 
            "JSON Serialization & Data Models", "State Machine Design for Games", "Local Machine Learning Integration",
            "Optimizing Python Memory & Speed", "Neural Network Visualizations"]
speakers = ["Dr. Aris Vance", "Elena Rostova", "Marcus Chen", "Sarah Jenkins", "Liam Thorne"]
rooms = ["Turing Auditorium", "Ada Lovelace Hall", "Hopper Lab", "Shannon Room"]
participants = ["Alex Mercer", "Beatrix Kiddo", "Carlos Mendez", "Diana Prince", "Erik Lindqvist", "Freja Jensen", 
                "Gideon Nav", "Hannah Abbott", "Ian Malcolm", "Julia Chang"]
topics = ["Artificial Intelligence", "Data Engineering", "User Interface Design", "Systems Architecture", "Game Development"]
time = ["09:00", "13:00"]
duration = ["90 minutes", "120 minutes", "150 minutes", "180 minutes"]
#Calling the function that generates a randomised schedule
event_lib = generate(sessions, speakers, rooms, topics, time, duration, participants)

#Print the whole dictionary
pprint.pprint(event_lib, indent=4, width=60)

#1. Print the title of the first session
print(event_lib[0]["title"])  
#2. Print the speaker of the third session.
print(event_lib[2]["title"]) 
#3. Print the room of the last session.
print(event_lib[-1]["room"]) 
#4. Print all information about one selected session.
#print(event_lib[3]) 
pprint.pprint(event_lib[3], indent=4, width=60)
#5. Print one specific value from a nested structure using chained indexing.
#Done in 1-3
#6. Print the first three sessions.
#print(event_lib[:3]) 
pprint.pprint(event_lib[:3], indent=4, width=60)
#7. Print the last two sessions.
#print(event_lib[-2:]) 
pprint.pprint(event_lib[-2], indent=4, width=60)
#8. Create a reversed version of the session schedule using slicing.
backwards = event_lib[::-1].copy()
#pprint.pprint(backwards, indent=4, width=60)
#9. Create a copy containing only part of the schedule.
partial = event_lib[2:-1]
#pprint.pprint(partial, indent=4, width=60)

#Unique Information
#Conference Topics
print("Conference topics:")
pprint.pprint(topics, indent=4, width=60)
#Unique Skills
#Not great, because it doesn't combine the topics for each speaker and 
#I didn't make sure sessions don't belong to relevant topics
#Can be fixed but seems unnecessary
print("Speaker topics:")
unique_skills2 = {event_lib[0]["speaker"] + " - " + event_lib[0]["topic"]}
unique_skills2.add(event_lib[1]["speaker"] + " - " + event_lib[1]["topic"])
unique_skills2.add(event_lib[2]["speaker"] + " - " + event_lib[2]["topic"])
unique_skills2.add(event_lib[3]["speaker"] + " - " + event_lib[3]["topic"])
unique_skills2.add(event_lib[4]["speaker"] + " - " + event_lib[4]["topic"])
unique_skills2.add(event_lib[5]["speaker"] + " - " + event_lib[5]["topic"])
unique_skills2.add(event_lib[6]["speaker"] + " - " + event_lib[6]["topic"])
unique_skills2.add(event_lib[7]["speaker"] + " - " + event_lib[7]["topic"])
pprint.pprint(unique_skills2, indent=4, width=60)
#Participants attending two or more sessions
multiple = event_lib[0]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"],event_lib[5]["participants"],event_lib[4]["participants"],event_lib[3]["participants"],event_lib[2]["participants"],event_lib[1]["participants"])
multiple.update(event_lib[1]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"],event_lib[5]["participants"],event_lib[4]["participants"],event_lib[3]["participants"],event_lib[2]["participants"]))
multiple.update(event_lib[2]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"],event_lib[5]["participants"],event_lib[4]["participants"],event_lib[3]["participants"]))
multiple.update(event_lib[3]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"],event_lib[5]["participants"],event_lib[4]["participants"]))
multiple.update(event_lib[4]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"],event_lib[5]["participants"]))
multiple.update(event_lib[5]["participants"].intersection(event_lib[7]["participants"],event_lib[6]["participants"]))
multiple.update(event_lib[6]["participants"].intersection(event_lib[7]["participants"]))
print(multiple)